### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by arpita739** [thatbrguy/Dehaze-GAN#14] opened 2020-06-19 20:36 UTC
![image](https://user-images.githubusercontent.com/40695939/85177848-cd781f80-b29e-11ea-9aec-dded92a27c0e.png)

**Comment by thatbrguy** [comment] 2020-07-24 19:17
Hello, sorry for the late response. 

In case the issue is still not resolved, it is most likely that the path that is passed in the function call `obj.test(os.path.join(os.getcwd(), 'model', 'checkpoint'))` (line 258 in `replicate.py`) does not point to the checkpoint directory. This issue might happen if you are **not** running the code from within the `legacy` folder. Can you let me know if you have tried running the code from inside the `legacy` folder?

If the issue has already been resolved, do let me know so that I can close this issue.

**Comment by thatbrguy** [comment] 2020-08-08 17:44
Closing issue due to inactivity.

**Closed as completed by thatbrguy** 2020-08-08 17:44 UTC
